name       : re2c
version    : 1.0.3
release    : 2
homepage   : http://re2c.org/
source     :
    - https://github.com/skvadrik/re2c/releases/download/1.0.3/re2c-1.0.3.tar.gz : cf56e0de3f335f6a22d3e8c06b8b450d858a4e7875ea1b01c9233e084b90cb52
license    : Public-Domain
component  : programming.tools
summary    : A tool for generating C-based recognizers from regular expressions
description: |
    re2c is a tool for writing very fast and very flexible scanners. Unlike any other such tool, re2c focuses on generating high efficient code for regular expression matching.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
