name       : re2c
version    : '3.0'
release    : 7
homepage   : http://re2c.org/
source     :
    - https://github.com/skvadrik/re2c/releases/download/3.0/re2c-3.0.tar.lz : 39757db2defc21a6713560cdff75895fb30f02af22a3ac8066fd9ba84f16a1b3
license    : Public-Domain
component  : programming.tools
summary    : A tool for generating C, C++ or Go based recognizers from regular expressions
description: |
    re2c is a tool for writing very fast and very flexible scanners. Unlike any other such tool, re2c focuses on generating high efficient code for regular expression matching.
setup      : |
    %configure
build      : |
    %make bootstrap
install    : |
    %make_install
check      : |
    %make check
