name        : re2c
version     : 0.15.3
release     : 1
homepage    : http://re2c.sourceforge.net/
source      :
    - http://downloads.sourceforge.net/project/re2c/0.15.3/re2c-0.15.3.tar.gz : f9d2a96c60a8c60d9c6c70e10590cbceaf0776d3115e7b3b35c7d7240cc1613b
license     : Public Domain
summary     : A tool for generating C-based recognizers from regular expressions
description : |
    re2c is a tool for writing very fast and very flexible scanners. Unlike any other such tool, re2c focuses on generating high efficient code for regular expression matching. 
setup       : |
    %configure --prefix="/usr" 
build       : |
    %make
install     : |
    %make_install DESTDIR="$installdir"
