name       : re2c
version    : 2.0.2
release    : 6
homepage   : http://re2c.org/
source     :
    - https://github.com/skvadrik/re2c/releases/download/2.0.2/re2c-2.0.2.tar.xz : 6cddbb558dbfd697a729cb4fd3f095524480283b89911ca5221835d8a67ae5e0
license    : Public-Domain
component  : programming.tools
summary    : A tool for generating C, C++ or Go based recognizers from regular expressions
description: |
    re2c is a tool for writing very fast and very flexible scanners. Unlike any other such tool, re2c focuses on generating high efficient code for regular expression matching.
setup      : |
    %configure
build      : |
    %make bootstrap
install    : |
    %make_install
check      : |
    %make check
