name       : re2c
version    : '1.3'
release    : 5
homepage   : http://re2c.org/
source     :
    - https://github.com/skvadrik/re2c/releases/download/1.3/re2c-1.3.tar.xz : f37f25ff760e90088e7d03d1232002c2c2672646d5844fdf8e0d51a5cd75a503
license    : Public-Domain
component  : programming.tools
summary    : A tool for generating C-based recognizers from regular expressions
description: |
    re2c is a tool for writing very fast and very flexible scanners. Unlike any other such tool, re2c focuses on generating high efficient code for regular expression matching.
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2020-11958.patch
    %configure
build      : |
    %make bootstrap
install    : |
    %make_install
check      : |
    %make check
